[package]
name = "subtree-merge"
version = "0.1.0"
authors = ["Rajat Sharma <lunasunkaiser@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-rs = { git = "https://github.com/rajatsharma/common-rs" }
